version: "3.4"
services: 
  api:
    image: ${DOCKER_REGISTER-}aspnetcore5-microservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=https://+;http://+"
      - "ASPNETCORE_HTTPS_PORT=8001"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore5microservices.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "8000:80"
      - "8001:443"
    restart: on-failure

