version: "3.4"
services: 
  api:
    image: ${DOCKER_REGISTER-}aspnetcore5-microservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - "8000:80"
    restart: on-failure

